# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  push_to_pratik_m:
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
      - name: Clone Production Repo
        uses: actions/checkout@v4.1.2
        with:
          path: './pratikm'
          repository: ${{ vars.PRODUCTION_URL }}
      - name: Clone Current Project Repo
        uses: actions/checkout@v4.1.2
        with:
          path: './build'
      - name: Copy file
        run: cp ./build/index.html ./pratikm/projects/bit/clock.html
      - name: Commit and push changes
        run: cd pratikm && git add . && git commit -m "Updated clock" && git push

        
